/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as i2 from 'ionic-angular/components/content/content';
import * as i3 from 'ionic-angular/config/config';
import * as i4 from 'ionic-angular/platform/platform';
import * as i5 from 'ionic-angular/platform/dom-controller';
import * as i6 from 'ionic-angular/components/app/app';
import * as i7 from 'ionic-angular/platform/keyboard';
import * as i8 from 'ionic-angular/navigation/view-controller';
import * as i9 from 'ionic-angular/navigation/nav-controller';
import * as i10 from './splash';
import * as i11 from 'ionic-angular/navigation/nav-params';
const styles_SplashPage:any[] = ([] as any[]);
export const RenderType_SplashPage:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_SplashPage,
    data:{}});
export function View_SplashPage_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n\n\n\n'])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'ion-content',[['padding',''],['style','background-color:deepskyblue']],
      [[2,'statusbar-padding',(null as any)],[2,'has-refresher',(null as any)]],(null as any),
      (null as any),i1.View_Content_0,i1.RenderType_Content)),i0.ɵdid(4374528,(null as any),
      0,i2.Content,[i3.Config,i4.Platform,i5.DomController,i0.ElementRef,i0.Renderer,
          i6.App,i7.Keyboard,i0.NgZone,[2,i8.ViewController],[2,i9.NavController]],
      (null as any),(null as any)),(_l()(),i0.ɵted(1,['\n\n'])),(_l()(),i0.ɵted((null as any),
      ['\n']))],(null as any),(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,2).statusbarPadding;
    const currVal_1:any = i0.ɵnov(_v,2)._hasRefresher;
    _ck(_v,1,0,currVal_0,currVal_1);
  });
}
export function View_SplashPage_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page-splash',
      ([] as any[]),(null as any),(null as any),(null as any),View_SplashPage_0,RenderType_SplashPage)),
      i0.ɵdid(49152,(null as any),0,i10.SplashPage,[i9.NavController,i11.NavParams],
          (null as any),(null as any))],(null as any),(null as any));
}
export const SplashPageNgFactory:i0.ComponentFactory<i10.SplashPage> = i0.ɵccf('page-splash',
    i10.SplashPage,View_SplashPage_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2p1c3Rpbi9kZXYvY3RzLWZpZWxkLXVzZXIvc3JjL3BhZ2VzL3NwbGFzaC9zcGxhc2gubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvanVzdGluL2Rldi9jdHMtZmllbGQtdXNlci9zcmMvcGFnZXMvc3BsYXNoL3NwbGFzaC50cyIsIm5nOi8vL1VzZXJzL2p1c3Rpbi9kZXYvY3RzLWZpZWxkLXVzZXIvc3JjL3BhZ2VzL3NwbGFzaC9zcGxhc2guaHRtbCIsIm5nOi8vL1VzZXJzL2p1c3Rpbi9kZXYvY3RzLWZpZWxkLXVzZXIvc3JjL3BhZ2VzL3NwbGFzaC9zcGxhc2gudHMuU3BsYXNoUGFnZV9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjwhLS1cbiAgR2VuZXJhdGVkIHRlbXBsYXRlIGZvciB0aGUgU3BsYXNoIHBhZ2UuXG5cbiAgU2VlIGh0dHA6Ly9pb25pY2ZyYW1ld29yay5jb20vZG9jcy92Mi9jb21wb25lbnRzLyNuYXZpZ2F0aW9uIGZvciBtb3JlIGluZm8gb25cbiAgSW9uaWMgcGFnZXMgYW5kIG5hdmlnYXRpb24uXG4tLT5cblxuXG5cbjxpb24tY29udGVudCBwYWRkaW5nIHN0eWxlPVwiYmFja2dyb3VuZC1jb2xvcjpkZWVwc2t5Ymx1ZVwiPlxuXG48L2lvbi1jb250ZW50PlxuIiwiPHBhZ2Utc3BsYXNoPjwvcGFnZS1zcGxhc2g+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0tHLDZDQUlIO01BQUE7TUFBQTtNQUFBLCtEQUFBO01BQUE7dUNBQUE7TUFBQSw2QkFBMEQsNkJBRTVDO01BQUE7SUFGZDtJQUFBO0lBQUEsV0FBQSxtQkFBQTs7OztvQkNUQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
