/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as i2 from 'ionic-angular/components/split-pane/split-pane';
import * as i3 from 'ionic-angular/components/nav/nav';
import * as i4 from 'ionic-angular/navigation/view-controller';
import * as i5 from 'ionic-angular/navigation/nav-controller';
import * as i6 from 'ionic-angular/components/app/app';
import * as i7 from 'ionic-angular/config/config';
import * as i8 from 'ionic-angular/platform/platform';
import * as i9 from 'ionic-angular/gestures/gesture-controller';
import * as i10 from 'ionic-angular/transitions/transition-controller';
import * as i11 from 'ionic-angular/navigation/deep-linker';
import * as i12 from 'ionic-angular/platform/dom-controller';
import * as i13 from './app.component';
import * as i14 from '@ionic-native/status-bar/index';
import * as i15 from '@ionic-native/keyboard/index';
import * as i16 from '@ionic-native/splash-screen/index';
import * as i17 from '../providers/user-manager';
import * as i18 from '../utils/utils';
const styles_MyApp:any[] = ([] as any[]);
export const RenderType_MyApp:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_MyApp,
    data:{}});
export function View_MyApp_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{nav:0}),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      2,'ion-nav',([] as any[]),(null as any),(null as any),(null as any),i1.View_Nav_0,
      i1.RenderType_Nav)),i0.ɵprd(6144,(null as any),i2.RootNode,(null as any),[i3.Nav]),
      i0.ɵdid(4374528,[[1,4],['ctsNav',4]],0,i3.Nav,[[2,i4.ViewController],[2,i5.NavController],
          i6.App,i7.Config,i8.Platform,i0.ElementRef,i0.NgZone,i0.Renderer,i0.ComponentFactoryResolver,
          i9.GestureController,i10.TransitionController,[2,i11.DeepLinker],i12.DomController,
          i0.ErrorHandler],{root:[0,'root']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i13.MyApp = _v.component;
    const currVal_0:any = _co.rootPage;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_MyApp_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_MyApp_0,RenderType_MyApp)),
      i0.ɵdid(114688,(null as any),0,i13.MyApp,[i8.Platform,i14.StatusBar,i15.Keyboard,
          i16.SplashScreen,i17.UserManager,i18.Utils],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const MyAppNgFactory:i0.ComponentFactory<i13.MyApp> = i0.ɵccf('ng-component',
    i13.MyApp,View_MyApp_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2p1c3Rpbi9kZXYvY3RzLWZpZWxkLXVzZXIvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2p1c3Rpbi9kZXYvY3RzLWZpZWxkLXVzZXIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvanVzdGluL2Rldi9jdHMtZmllbGQtdXNlci9zcmMvYXBwL2FwcC5odG1sIiwibmc6Ly8vVXNlcnMvanVzdGluL2Rldi9jdHMtZmllbGQtdXNlci9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuTXlBcHBfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aW9uLW5hdiAjY3RzTmF2IFtyb290XT1cInJvb3RQYWdlXCI+PC9pb24tbmF2PlxuIiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O2lEQ0FBO01BQUE7dUJBQUE7YUFBQTs7d0RBQUE7eUJBQUEsbUNBQTZDO1VBQUE7O0lBQTVCO0lBQWpCLFdBQWlCLFNBQWpCOzs7O29CQ0FBO01BQUE7YUFBQTtvREFBQTs7UUFBQTs7OzsifQ==
